#!/bin/sh

# TODO: 
# dwm
# dwmblocks
# xinit
# pipewire
# networkmanager?
# kbd
# world
# 

cd ~/dotfiles

worldset() {
}

dwm() {
	cd ~/compiles/dwm-6.5/
	doas make install
}

dwmblocks() {
}

xinit() {
}

pipewire() {
}

networkmanager() {

}

keyboard() {
	ln -s dvcustom /usr/share/X11/xkb/symbols/dvcustom
}
