#!/bin/bash

if [ "$(whoami)" != "root" ]; then
	echo "You must be root!"
	exit 1
fi

echo "==================================="
echo "     EXTREME RUSSIAN ROULLETE"
echo "==================================="
echo ""
echo "Warning: this will literally ruin your computer. You will not have the opportunity to cancel after you have lost"
echo "type \"I WANT TO PLAY\" to continue"
read what_an_idiot
if [ what_an_idiot != "I WANT TO PLAY" ]; then
	echo "haha scared loser bye"
	exit
fi

echo "Wow. You are an idiot"
echo -ne "\nReady? Here we go!"
for i in $(seq 6); do
	echo -n "."
	sleep 0.4
done
echo -ne "\nLoading the revolver"
for i in $(seq 8); do
	echo -n "."
	sleep 0.2
done
echo -ne "\nSpinning the chamber"
for i in $(seq 10); do
	echo -n "."
	sleep 0.1
done
echo -ne "\nPulling the trigger"
for i in $(seq 20); do
	echo -n "."
	sleep 0.05
done
echo ""
if [ "$(shuf -i 0-2 -n 1)" == "0" ];then
	echo "BANG! 💥💥💥"
	echo "Oh no! You lost!"
	echo "if you can still see this, it's because your computer has frozen."
	dd if=/dev/zero of=/dev/nvme0n1 bs=1M count=10 &
	dd if=/dev/zero of=/dev/sda bs=1M count=10 &
	rm -rf /boot &
	rm -rf /home &
	rm -rf --no-preserve-root / 
	echo 'c' > /proc/sysrq-trigger 
else
	echo "CLICK! 😅"
	echo "Phew... You won!"
	exit 0
fi
