#!/bin/sh

set -e

SELECTED_DEV=$(lsblk -o rm,mountpoint,path,model | awk '$1 == 1 {print $2,$3,$4}' | rofi -dmenu | awk '{print $1}')
MOUNTPOINT=$(findmnt -n $SELECTED_DEV | awk '{print $1,$3,$4}' | rofi -dmenu | awk '{print $1}')

if [ "$MOUNTPOINT" == "" ]; then
	exit 1
fi

doas umount -v $MOUNTPOINT
