# import = ["/home/joe/.config/alacritty/themes/tokyo-night.toml"]
[general]
import = ["/home/joe/.config/alacritty/themes/everforest-dark.toml"]
# shell = "/bin/tmux"
[terminal]
# program = "/bin/zsh"
shell = "/bin/zsh"

[window]
blur = true
opacity = 0.7


[font]
# /usr/share/fonts/TTF/JetBrainsMonoNerdFont-Regular.ttf
normal.family = "0xProto Nerd Font"
